import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Login.module.css';
import { useState, useEffect, useRef } from 'react';
import logo from '../../public/logo.png';
import validationEmail from '../utils/validationEmail';
import globalUrl from '../utils/urlApi';

export default function Login() {
  const [inputEmail, setInputEmail] = useState('');
  const [inputPassword, setInputPassword] = useState('');
  const [enableButton, setEnableButton] = useState(true);
  const [errorMessage, setErrorMessage] = useState(``);
  const emailInput = useRef(null);

  useEffect(() => {
    if (validationEmail(inputEmail) && inputPassword.length >= 8) {
      setEnableButton(false);
    } else {
      setEnableButton(true);
    }
  }, [inputEmail, inputPassword]);

  useEffect(() => {
    if (emailInput.current) {
      emailInput.current.focus();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();

    const payload = {
      email: inputEmail,
      password: inputPassword,
    };

    try {
      const response = await fetch(`${globalUrl}:3001/login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const data = await response.json();
      if (data.message) {
        return setErrorMessage(`Email ou senha incorretos`);
      }

      const { token } = data;
      window.localStorage.setItem('token', token);

      window.location.href = '/home';
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.containerLogo}>
          <Image src={logo} alt="Logo" width={150} height={150} />
        </div>
        <form
          className={styles.formContainer}
          onSubmit={(e) => handleSubmit(e)}
        >
          <input
            type="text"
            placeholder="Email"
            className={styles.input}
            ref={emailInput}
            value={inputEmail}
            onChange={(e) => setInputEmail(e.target.value)}
          />

          <input
            type="password"
            placeholder="Password"
            className={styles.input}
            value={inputPassword}
            onChange={(e) => setInputPassword(e.target.value)}
          />

          {errorMessage && (
            <p className={styles.errorMessage}>{errorMessage}</p>
          )}

          <button
            type="submit"
            className={styles.button}
            disabled={enableButton}
          >
            Entrar
          </button>
        </form>
        <a className={styles.changePasswordLink} href="#">
          Esqueci minha senha
        </a>
      </main>
    </div>
  );
}
